### ISSUE TITLE
Incompatible with new graphql-ruby AST (>=1.10)

### ISSUE THREAD

**Issue by j15e** [sunny/graph_attack#7]
I just tried to use this gem but it seems like the analyzer is not compatible with the "new" graphql-ruby AST. It is opt-in, so the gem still works if we don't opt-in the new analyzer, but I think its the new default.

I think those breaking changes were introduced in [graphql-ruby 1.10.0](https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG.md#1100-20-jan-2020), and the linked PR [2363](https://github.com/rmosolgo/graphql-ruby/pull/2363) is pretty huge.

> Class-based schemas using the interpreter must add use GraphQL::Analysis::AST to their schema (and update their custom analyzers, see https://graphql-ruby.org/queries/ast_analysis.html) #2363

Any idea of the scope of changes required?

**Comment by sunny** [comment]
Hey @j15e! I am not using the new format so that's not something I had on my radar.

I am not sure of how much change is required, but it doesn't seem to harsh.

Most of the glue code for fields is currently calling [accepts_definitions](https://github.com/sunny/graph_attack/blob/main/lib/graph_attack/metadata.rb). Now, it seems to me that apps need to [define a custom field](https://graphql-ruby.org/type_definitions/extensions.html#customizing-fields) e.g. `field_class GraphAttack::RateLimitedField` so that the `rate_limit:` option adds the info to its metadata. (Or this gem should perhaps inject itself into `Types::BaseObject`?)

Would you like to give it a try?

**Comment by j15e** [comment]
Thanks for the help! I think I can indeed now define limits on my fields by adding a method to my custom field class instead of relying on accept_definitions, like this : 

```ruby
# app/graphql/types/base_field.rb
module Types
  class BaseField < GraphQL::Schema::Field
    argument_class Types::BaseArgument

    attr_reader :threshold
    attr_reader :interval

    def rate_limit(threshold: nil, interval: nil)
      @threshold = threshold
      @interval = interval
    end
  end
end

# app/graphql/types/query_type.rb

module Types
  class QueryType < Types::BaseObject
    field :users, [Types::Objects::UserType], null: false do
      description "Returns a list of users"
      rate_limit threshold: 15, interval: 60
    end
  end
end
```

But then the gem analyzer still need some other changes I think because I get the following error when running queries : 

```
wrong number of arguments (given 1, expected 0)
graph_attack-1.1.0/lib/graph_attack/rate_limiter.rb:12:in `initialize'
graphql-1.11.2/lib/graphql/analysis/ast.rb:58:in `new'
graphql-1.11.2/lib/graphql/analysis/ast.rb:58:in `block (2 levels) in analyze_query'
graphql-1.11.2/lib/graphql/analysis/ast.rb:58:in `map'
graphql-1.11.2/lib/graphql/analysis/ast.rb:58:in `block in analyze_query'
graphql-1.11.2/lib/graphql/tracing.rb:81:in `call_tracers'
graphql-1.11.2/lib/graphql/tracing.rb:83:in `block in call_tracers'
graphql_devise-0.13.1/lib/graphql_devise/schema_plugin.rb:25:in `trace'
graphql-1.11.2/lib/graphql/tracing.rb:83:in `call_tracers'
graphql-1.11.2/lib/graphql/tracing.rb:67:in `trace'
graphql-1.11.2/lib/graphql/analysis/ast.rb:56:in `analyze_query'
graphql-1.11.2/lib/graphql/analysis/ast.rb:32:in `block (2 levels) in analyze_multiplex'
graphql-1.11.2/lib/graphql/analysis/ast.rb:30:in `map'
graphql-1.11.2/lib/graphql/analysis/ast.rb:30:in `block in analyze_multiplex'
graphql-1.11.2/lib/graphql/tracing.rb:81:in `call_tracers'
graphql-1.11.2/lib/graphql/tracing.rb:83:in `block in call_tracers'
graphql_devise-0.13.1/lib/graphql_devise/schema_plugin.rb:25:in `trace'
graphql-1.11.2/lib/graphql/tracing.rb:83:in `call_tracers'
graphql-1.11.2/lib/graphql/tracing.rb:67:in `trace'
graphql-1.11.2/lib/graphql/analysis/ast.rb:29:in `analyze_multiplex'
graphql-1.11.2/lib/graphql/execution/multiplex.rb:194:in `block in instrument_and_analyze' 
```

I thinks its another change they introduced that now you must provide a class rather than an instance of a class to define extra analyzer like this and they now pass [the query as the initialize argument](https://graphql-ruby.org/queries/ast_analysis.html#analyzer-api) : 

```ruby
class MyAppSchema < GraphQL::Schema
  # Before it was : 
  # query_analyzer GraphAttack::RateLimiter.new
  # Now it must be :
  query_analyzer GraphAttack::RateLimiter
  # ...
end
```

So I think `GraphAttack::RateLimiter` would need to be updated to support that new API, or perhaps the gem could provide another class like `GraphAttack::RateLimiterNewEngine` (for the lack of a better name) to support the new AST.

**Comment by sunny** [comment]
I didn't manage to use the new AST Analyzer since it was missing the context at that time of parsing. However, when using the new field extensions API, it works like a charm 🎉

Would you mind trying it out on your side? For that you should:

1. Update your Gemfile to point to the temporary branch:

```rb
# GraphQL analyser for blocking & throttling by IP.
gem 'graph_attack',
    github: 'sunny/graph_attack',
    branch: 'allow-class-based-syntax'
```

2. Remove your schema's `query_analyzer` line.

3. Replace `rate_limit` calls by `extension(GraphAttack::RateLimit, threshold: …, interval: …)`

**Comment by sunny** [comment]
Hey @j15e, does it work as intended on your side with that branch?

**Comment by j15e** [comment]
Sorry, I have not had time to test and I no longer work actively on the project concerned by the issue =/ but I think it should work

**Comment by sunny** [comment]
It’s due for a merge then, thanks for reporting!
